//! Diesel schema definition, mirroring migrations/20250805000000_initial.
//!
//! Generated by hand from the migration SQL. Column order follows the CREATE
//! TABLE statements; keep it in sync if the schema evolves.

diesel::table! {
    projects (id) {
        id -> Integer,
        name -> Text,
        sort_order -> Integer,
        created_at -> Text,
    }
}

diesel::table! {
    notes (id) {
        id -> Integer,
        project_id -> Integer,
        content_md -> Text,
        created_at -> Text,
        updated_at -> Text,
    }
}

diesel::table! {
    attachments (id) {
        id -> Integer,
        note_id -> Integer,
        kind -> Text,
        mime -> Text,
        file_name -> Text,
        created_at -> Text,
    }
}

diesel::table! {
    settings (key) {
        key -> Text,
        value -> Text,
    }
}

diesel::joinable!(notes -> projects (project_id));
diesel::joinable!(attachments -> notes (note_id));

diesel::allow_tables_to_appear_in_same_query!(projects, notes, attachments, settings);
